### ISSUE TITLE
History access?

### ISSUE THREAD

**Issue by EdBoraas** [al-caughey/Google-Meet-Attendance#1]
The extension on the Chrome Store requests access to browser history. Is that correct? If so, would it be possible to explain in the README why that permission is needed?

Thank you!

**Comment by al-caughey** [comment]
Ed - Ah... no, I don't know why it would be asking for that.  Can you send a screenshot?
TIA

**Comment by EdBoraas** [comment]
Sure! It's odd, because I don't see that permission listed in the manifest.json in this repo. (I don't know anything about Chrome Extension development, so I may be looking at the wrong thing.)

![image](https://user-images.githubusercontent.com/1393653/79588887-d4619680-8091-11ea-837d-9b9e3c41d02e.png)

**Comment by al-caughey** [comment]
Ed - thanks for the nudge... I'd been busy testing and fixing things locally and updating things at the chrome store so things got out of sync here.
The files are now up-to-date... in particular, the manifest now shows that the permissions include storage and tabs.

Based upon a quick read, the tabs permission (which was need to show/hide options in the popup) is what triggered `read your browsing history` notification.  I presume that Google is showing that because if you look at the full features of the tab functionality, the extension could read that info.

I am not!

**Comment by al-caughey** [comment]
With that, I'm going to mark the issue as closed... let me know if you have any objections
