### ISSUE TITLE
Class list incomplete and "Hide Participants" showing up

### ISSUE THREAD

**Issue by mrsbryan** [al-caughey/Google-Meet-Attendance#14]
Hi,

First off Thank you so much for creating this extension.  It is invaluable for teachers doing classes virtually. 

My issue is that the class list that is showing up in my attendance is not matching the people present in the google meet.  I didn't have the foresight to take a clear screenshot before i closed the meet but here is what mine looks like.  I had 46 people on the meet, and less than half a dozen were showing up on the class list. 

![image](https://user-images.githubusercontent.com/64600432/80729052-5065d080-8acd-11ea-9173-5b71fdb0b260.png)
![google attendance screenshot](https://user-images.githubusercontent.com/64600432/80729171-74291680-8acd-11ea-9aab-948514825091.png)

As well "Hide participant" text is showing up on top of a few of the names, and I have no idea what that means, or how to "unhide" the participant.  

Lastly, the previous version allowed me to move the attendance box anywhere on the screen whereas now it is fixed in one spot.  Can that functionality be returned?

**Comment by al-caughey** [comment]
RE: missing the students... did they join before you?  Did you go to the Peoples tab and scroll to the bottom... that usually get things in sync for me

I just notice the Hide Participants too?!? it looks like Google maybe changed something.  I will have to investigate

I removed the jQuery libriaries that allowed you to drag the dialog around the screen.  I don't want to re-add the libraries because it is a lot of overhead for just one feature.  But I miss it too.  I will fake the draggable feature in my own JS code.

**Comment by mrsbryan** [comment]
They did join before me, and I did scroll to the bottom of the peoples tab.  I was trying to see how the class list was coinciding with the "people" list and it didn't make much sense who was listed and who wasn't.  Many of the students were in the meet before my arrival, I do this on purpose for the students social benefit.  Some may not necessarily message each other privately, but when they show up to class (like in a physical class) they have some time to say hi and chat to one another before the teacher arrives and class starts.

**Comment by mrsbryan** [comment]
As a note - they have joined the meet before me in the past, and this wasn't an issue with the google meet attendance in the previous version.

**Comment by al-caughey** [comment]
It looks like Google has changed the structure of their page (and added hide participant).  Were or are you using the Grid View Extension?  When it is turned on, the attendance is taken as expected because all of the participants are listed on the screen.  If not, Google only shows 5-6 participants down the right edge of the screen (and does not seem to offer a simple way to list who's there... hence having to check the People tab)

Al

**Comment by mrsbryan** [comment]
I will try to play around with it more.  I had the newly added tiled 16 person grid up.  I have used grid view in the past, but lately it has been glitchy - especially in the glasses with 30+ kids and the students are toggling their videos and mics on and off.

**Comment by AlCaughey** [comment]
I'm pretty sure it was/is grid view that was creating the 'hide participant' entries. Regardless, they should not appear once you get v0.4.5

**Comment by al-caughey** [comment]
I'm going to close this now... OK?

**Comment by mrsbryan** [comment]
Yes. Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
