### ISSUE TITLE
Class list 

### ISSUE THREAD

**Issue by Sydneybr0307** [al-caughey/Google-Meet-Attendance#33]
For some reason this morning when I logged in to google meet, my class lists were not there, and it wouldn't let me add any more names. How do I re-add names and classes?

**Comment by al-caughey** [comment]
Can you send me screenshot?

**Comment by al-caughey** [comment]
Have you also installed Meet Attendance or the Chat Transcribe extension
(by claycodes.org) ? If yes, they both use a CSS library that changes the
expected appearance of html elements and cause problems in other extensions

**Comment by Sydneybr0307** [comment]
Never mind. I just restarted my computer. It’s fine now. I love this
extension by the way!!

**Comment by Sydneybr0307** [comment]
I haven’t installed those

**Comment by al-caughey** [comment]
Were you perhaps logged with a different Google Profile?  e.g., home profile rather than work?

My extension saves your class names and lists using the Google Sync Service which means that they are tied to your Google profile (so they are available on every laptop/desktop/chromebook where you login with the same credentials

But, they're not there if you login with a different profile

**Comment by al-caughey** [comment]
closed as per comments above
