### ISSUE TITLE
Split Screen Bug and Tab change

### ISSUE THREAD

**Issue by luckyhero613** [al-caughey/Google-Meet-Attendance#56]
While split screen in PC, In one attending meet and in other watching movies or else. then in that case it shows full attendance. that's not good though. one more thing teachers can't display presentation so one have to open book in other tab(same like open book in class), then in that case it shows user not attending class. thats not good though. 
If it is possible that teacher can get which app the user opened else than meet, and user given condition that if user opened any Document viewer, google classroom, then it will count to attendance but other than if not satisfy condition then don't count attendance of user.

Thank you
Ankit Gupta

**Comment by Eagle-Man** [comment]
No, that's not possible because Google does not provide access to the back end of Meet to third-party developers.  All the information that the extension uses is scraped from the HTML source code.  So it only knows if the participant is on the screen (present) or not on the screen (not present).  If you would like to present, join the same Meet in a second tab and join in Present mode (not "Join Now").  This way, the first tab will continue to record attendance because it still has all the video feeds, and the second can present to the Meet.  Even better if you have 2 devices (laptop and desktop) or two monitors.

**Comment by luckyhero613** [comment]
that's not how user friendly things work. we will have to improve the Google Attendance Extension. because I surveyed and most of the user attended meet of 1 hr but it showed just 0 min to 1 min for more than 90% user. and to check their activeness in every 5 minutes I get their audible response. so It's not favourable that user attend  60 min and extension show 1 min.

**Comment by Eagle-Man** [comment]
It's not that he doesn't want to make it work that way, but that it's just not possible with what is available to him from the Meet.  The entire extension is a giant work around because there's no API for Google Meet, so there's really nothing that can be done about it.  If the participant's name doesn't appear on the screen in the Meet, the extension can't find it and then it doesn't know if they are there.

Sorry.  Presently, based on how Google has set up Meets, the second Meet is the only option for presenting and using attendance.  Note that you don't need to be showing the Meet with the video feeds all the time.  As long as that tab exists, then it can capture the data in the background.  Also, I forgot to mention that since it's looking for names in the HTML code, all participants must be shown on the screen at the same time in order to capture fully.  The easiest way to do this is to have another extension like Grid View (fix).  Another possibility is to leave the Participants panel open all the time.  If that doesn't work for you, then you might need to find another solution.

**Comment by al-caughey** [comment]
You raise two issues
1. accuracy, and
2. attentiveness.

RE: attentiveness.  My extension runs only on the teacher's computer so it
has no idea of what is happening on the students' devices.  Given the the
range of possible devices that the students might be using, it would be
hard (if not impossible) for a third party developer to create something
that monitored what they (else) they are doing on their devices during the
Meet.  This would be best handled by Google in their Meet Mobile app and/or
Meet web code.

RE: accuracy - as previously described, Google does not make it easy to
take and monitor attendance.  They do not provide an API (application
programming interface) that allows third party developers to see who is in
the Meet... even though they know that info).  So I (and all others who are
creating attendance extensions) have to adopt strategies to figure out
who's joined and whether they are still there.  My strategy is to `look` at
the Meet screen and see who's showing (that is, I look for a particular set
of HTML elements on the page and then extract the names from them --> to
see exactly how I do that, take a look at my extension code here at
GitHub).

To make things more complicated, in large Meets, Google only keeps the most
active participants showing on the screen... those who have their cameras
on; those who have their mics on and are talking (and I think those who are
chatting).  The others are removed from the screen so you, as the teacher,
do not know if they're still there (and, for me, Google deletes the HTML
elements mentioned above, so I don't know if they are still there either).

With small classes, using the built-in Tiled layout is good because it
keeps up to 16 students on the screen (Google will increase that to 49
soon).  Otherwise, the Grid View (fix) extension is the best option that
I've seen to keep *all* of the students showing.  My biggest Meets have
been staff meetings with up to 80-90 participants but one user told me he
had  140 in his class (and attendance was taken properly!).

In addition to looking at the avatars on the screen, I also detect the
`__________ has joined...` messages but those are not always helpful
because if several students join at the same time, the message is changed
to `______ and 3 others have joined` and Google does not say who the others
are.
And, like the other extensions, I also detect names in the People pane but,
again, that is an unreliable technique because it means that you can only
monitor attendance when that pane is open.  Further, the People pane, like
the main screen, only shows a few of the participants so you have to
manually scroll to the bottom of that list to see everyone on the Meet.
IMHO, it is a PITA to have to do that repeatedly to see who's still in the
Meet and I want to watch the Chat pane rather than the People pane.

I truly appreciate the feedback - thank you!  Teachers like you have help
me improve the extension and I am thankful for that.

**Comment by luckyhero613** [comment]
Thank you Al-Caughey, I hope that Google meet team will support your work more as your Attendance Extension demands increasing.

**Comment by luckyhero613** [comment]
Also thank you to @Eagle-Man  for clarifying the issue : )
